---
title: "BTI 2022 World Map"
author: "Deviana Dewi"
date: '2022-05-17'
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
setwd("~/Desktop")
BTI_2022 <- read.csv("BTI_2022.csv",sep = ";",header = TRUE)
View(BTI_2022)
```

```{r}
library(rworldmap)

#Create a world mapthat makes a connection between country (without the code so it will be "NAME") and the column country_name 
WorldMap_BTI_Coordination <- joinCountryData2Map(BTI_2022, joinCode = "NAME", nameJoinColumn = "Country")
par(mai=c(0,0,0.2,0),xaxs="i",yaxs="i")
mapCountryData(WorldMap_BTI_Coordination, nameColumnToPlot = "Coordination", mapTitle = "BTI Policy Coordination, 2022", colourPalette = c("#e0f3db","#ccebc5","#a8ddb5","#7bccc4","#4eb3d3","#2b8cbe","#0868ac","#084081"), oceanCol = "gray", missingCountryCol = 'white') 
``` 

``` {r}
#Create a world mapthat makes a connection between country (without the code so it will be "NAME") and the column country_name 
WorldMap_BTI_Implementation <- joinCountryData2Map(BTI_2022, joinCode = "NAME", nameJoinColumn = "Country")
par(mai=c(0,0,0.2,0),xaxs="i",yaxs="i")
mapCountryData(WorldMap_BTI_Implementation, nameColumnToPlot = "Implementation", mapTitle = "BTI Policy Implementation, 2022", colourPalette = c("#e0f3db","#ccebc5","#a8ddb5","#7bccc4","#4eb3d3","#2b8cbe","#0868ac","#084081"), oceanCol = "gray", missingCountryCol = 'white') 
```
