---
title: "VDem World Map"
author: "Deviana Dewi"
date: '2022-05-05'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(rworldmap)
```

```{r}
setwd("~/Desktop")
VDem_Data <- read.csv("vdem.csv",sep = ",",header = TRUE)
View(VDem_Data)
```

```{r}
#Create new dataset only with select columns 

VDem_Data1 <- subset(VDem_Data,select = c(country_name, year,v2x_accountability_osp))
VDem_Data1 <- VDem_Data1 [which(VDem_Data1$year=="2021"),]
View(VDem_Data1)

``` 

``` {r}
#Create a world mapthat makes a connection between country (without the code so it will be "NAME") and the column country_name 
mapworld <- joinCountryData2Map(VDem_Data1, joinCode = "NAME", nameJoinColumn = "country_name")
``` 
``` {r}
par(mai=c(0,0,0.2,0),xaxs="i",yaxs="i")
mapCountryData(mapworld, nameColumnToPlot="v2x_accountability_osp" , mapTitle = "VDem Accountability Index, 2021", colourPalette = c("#e0f3db","#ccebc5","#a8ddb5","#7bccc4","#4eb3d3","#2b8cbe","#0868ac","#084081"), oceanCol = "gray", missingCountryCol = 'white') 
``` 
```{r}
setwd("~/Desktop")
VDemCSO_Data <- read.csv("VDemCSO.csv",sep = ",",header = TRUE)
View(VDemCSO_Data)
```

```{r}
library(rworldmap)
#Create a world mapthat makes a connection between country (without the code so it will be "NAME") and the column "country_name" 
mapworld <- joinCountryData2Map(VDemCSO_Data, joinCode = "NAME", nameJoinColumn = "country_name")
par(mai=c(0,0,0.2,0),xaxs="i",yaxs="i")
mapCountryData(mapworld, nameColumnToPlot="v2xcs_ccsi" , mapTitle = "VDem Core Civil Society Index, 2021", colourPalette = c("#e0f3db","#ccebc5","#a8ddb5","#7bccc4","#4eb3d3","#2b8cbe","#0868ac","#084081"), oceanCol = "gray", missingCountryCol = 'white')
```