---
title: "Indicator 30"
author: "Destan Aytekin"
date: '2022-05-24'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
#Preparing libraries
library(gt)
library(tidyverse)
library(dplyr)
library(tidyr)
library(ggplot2)

View(FAOSTAT_indicator_30_2019_data)

#Merging the dataset with World Bank classifications
data_indicator30 <- merge(FAOSTAT_indicator_30_2019_data, World_Bank_Classifications, by = "Country")
#63 observations was lost when merged with WB classifications (dropped from 213 to 150 observations).
#2019 data is used as it was most the recent year of data with good country coverage.

```

## Including Plots

You can also embed plots, for example:

```{r pressure}
data_indicator30 %>% ggplot(aes(WBRegion,Value)) + ylab('Availability/supply (g/day/capita) - fruits') + geom_boxplot() + geom_point()

data_indicator30 %>% ggplot(aes(WBIncome,Value)) + ylab('Availability/supply (g/day/capita) - fruits') + geom_boxplot() + geom_point()
```
