---
title: "Indicator 3"
author: "Destan Aytekin"
date: '2022-05-24'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

##Indicator 2: Zero fruit and vegetable consumption among infants and young children(age 6-23 months)

```{r}

#Prep necessary libraries 
library(gt)
library(tidyverse)
library(dplyr)
library(tidyr)
library(ggplot2)
View(unicefdata_for_whisker_plot_2)
```

```{r}
#Merge the dataset with World Bank classifications
data_indicator2_2019 <- merge(UNICEF_Zero_Fruits_and_Vegetables_Consumption_2019_data, World_Bank_Classifications, by = "Country")
#49 observations were lost when the dataset is merged with World Bank classifications, as the country names were absent from the World Bank list.
```

```{r}
#Plot the median for each region for 2019 - same code replicated for generating box plot for World Bank Income levels by hyst changing WBRegion into WBIncome in the code below.

data_indicator2_2019 %>% ggplot(aes(WBRegion,Value)) + ylab('Proportion of Zero Consumption of Fruits and Vegetables') + geom_boxplot() + geom_point()
```
