---
title: "Iodine"
author: "Deviana Dewi"
date: '2022-05-27'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
#iodine_data is the original dataset in Excel from the website 
#iodine_data_clean is the long dataset in Excel with all years for each country
#iodine_data_latest is the clean dataset in CSV (an outcome from some data restructing using STATA) -- this is the dataset I used for the map in R
setwd("~/Desktop")
Iodine <- read.csv("iodine_data_latest.csv",sep=",",header = TRUE)
View (Iodine)
```

```{r}
library(rworldmap)
#Create a world map that makes a connection between country (without the code so it will be "NAME") and the column country_name 
WorldMap_Iodine <- joinCountryData2Map(Iodine, joinCode = "NAME", nameJoinColumn = "Country")
par(mai=c(0,0,0.2,0),xaxs="i",yaxs="i")
mapCountryData(WorldMap_Iodine, nameColumnToPlot = "Estimate", mapTitle = "Coverage of iodized salt (% of households)", colourPalette = c("#e0f3db","#ccebc5","#a8ddb5","#7bccc4","#4eb3d3","#2b8cbe","#0868ac","#084081"), oceanCol = "gray", missingCountryCol = 'white') 
``` 